version: "3"

services:
  whisper-frontend:
    container_name: whishper-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    env_file:
      - .env
    volumes:
      - ../uploads:/app/uploads
   